### ISSUE TITLE
Preload extension adding syntax highlighting to vyper

### ISSUE THREAD

**Issue by krzkaczor** [dethcrypto/ethereum-code-viewer#16]
Orginal request: https://twitter.com/wei3erHase/status/1471530138231844869

**Comment by hasparus** [comment]
Vyper's extension doesn't work in the web. We can fork it and try to enable it by removing, but there is an alternative solution — using Python's syntax highlighting for `.vy` extension.

**Comment by krzkaczor** [comment]
Are they compatible on syntax level?

**Comment by hasparus** [comment]
> Are they compatible on syntax level?

Actually, I think we'd have to base some edits to the grammar on Vyper repo anyway.
The approach I decided to go with after some research and consideration is forking the Vyper extensions (and possibly contributing the change upstream).

**Comment by krzkaczor** [comment]
Done via: https://github.com/dethcrypto/ethereum-code-viewer/pull/30
