### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by krzkaczor** [dethcrypto/ethereum-code-viewer#28]
https://etherscan.deth.net/address/0x60f80121c31a0d46b5279700f9df786054aa5ee5

https://twitter.com/elyx0/status/1473468964244234247?s=21

**Comment by hasparus** [comment]
> Didn't work for https://etherscan.deth.net/address/0x60f80121c31a0d46b5279700f9df786054aa5ee5 source should contain "ERC1155" a few times, but not on deth.


Should it truly contain `"ERC1155"`?

In Etherscan `#code` UI, it's a single file, also without any `"ERC1155"` mention.
https://etherscan.io/address/0x60f80121c31a0d46b5279700f9df786054aa5ee5#code

**Comment by krzkaczor** [comment]
I think that original reporter thought that `IERC721`'s source would be extracted to a separate file. But we are not doing this. Files are separated only if multi-file verification was used on etherscan. I am closing this.

**Comment by hasparus** [comment]
> Files are separated only if multi-file verification was used on etherscan. I am closing this.

I considered splitting them, but we'd have to add imports and that seems like a heavy modification :>

**Comment by krzkaczor** [comment]
Yeah. It's not a trivial problem (also there is a ton of different solidity versions to support...) but who knows, maybe in future, we could implement this.

**Comment by Elyx0** [comment]
It's me folks I'm sorry I lost you time I think I mixed up RARI Token 2 and RARI Token 3 ... https://etherscan.deth.net/address/0xd07dc4262bcdbf85190c01c996b4c06a461d2430#code does contain ERC1155. I apologize.
