### ISSUE TITLE
Support all etherscan supported chains

### ISSUE THREAD

**Issue by krzkaczor** [dethcrypto/ethereum-code-viewer#7]
From the top of my head:
- [ ] ethereum testnets (kovan, ropsten, goerli)
- [ ] L2s (arbiscan, optimism + testnets)
- [ ] sidechains (bsscan, polygon, xdai)
- [ ] L1s (avax?, moonriver?)

**Comment by chainvisions** [comment]
Would be great to have it for Fantom as well (Ftmscan). Also Etherscan does not have support for xDai.

**Comment by BrokedTV** [comment]
BSC pls

**Comment by krzkaczor** [comment]
Done in https://github.com/dethcrypto/ethereum-code-viewer/pull/21
